version: '3'
services:
#   container for mysql
  databasemysql:
    image: mysql:8.0.17
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql-doc
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_USER: dbuser1
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: testdb

#    container for mongo
  databasemongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    container_name: mongo-con
    network_mode: host
    environment:
      MONGO_DATABASE: noteDb



#   container for user module
  usermodule:
      build:
        dockerfile: Dockerfile
        context:  ./UserModule
      container_name: usermodule-docker
      network_mode: host
      restart: always
      ports:
       - "8002:8002"
      depends_on:
        - databasemysql
        
#   container for favourite module
  favouritemodule:
      build: 
        dockerfile: Dockerfile
        context:  ./FavouriteModule
      container_name: favouritemodule-docker
      network_mode: host
      restart: always
      ports:
       - "8001:8001"
      depends_on:
        - databasemongo

#   container for recommend module
  recommendmodule:
      build: 
        dockerfile: Dockerfile
        context:  ./RecommendModule
      container_name: recommendmodule-docker
      network_mode: host
      restart: always
      ports:
       - "8003:8003"
      depends_on:
        - databasemongo



# container for front end 
  angular-frontend:
    build:
       dockerfile: Dockerfile
       context:  ./MusicApp
    container_name: angular-docker
    network_mode: host
    restart: always
    ports:
       - "8006:8006"
    
