FROM openjdk
WORKDIR /usr/src

COPY ./target/FavouriteModule-0.0.1-SNAPSHOT.jar FavouriteModule-0.0.1-SNAPSHOT.jar
#EXPOSE 8001
ENTRYPOINT ["java","-jar","/usr/src/FavouriteModule-0.0.1-SNAPSHOT.jar"]